# Generated by Django 3.2.8 on 2023-10-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBanco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_banco',
            name='genero',
            field=models.IntegerField(),
        ),
    ]
